INFRA-239 :: Fix - Added per page retry strategy
PokaInc/cfn-cross-region-export pull request #19
Opened 2020-12-18 21:19 UTC by daxAKAhackerman

This PR modifies the retry strategy so that if we hit a rate limit on the list_exports operation, the retry is executed on the page it was trying to fetch instead from starting the paging back from page one. 

The modification on line 124 is to remove a linter error since `label` was not used. 

The `requests` version was bumped since it generated dependencies error when installing `boto3`

2020-12-18 22:02 UTC, g-pelletier approved these changes

2020-12-21 19:31 UTC, laurrentt requested changes

2020-12-21 19:31 UTC, laurrentt commented on importer/lambda/cross_region_importer.py
> +            if all(export_state for export_state in exports_tracker.values()):
No list comprehension needed here
```suggestion
            if all(exports_tracker.values()):
```

2020-12-21 19:57 UTC, daxAKAhackerman commented on importer/lambda/cross_region_importer.py
> +            if all(export_state for export_state in exports_tracker.values()):
Indeed!

2020-12-21 21:59 UTC, laurrentt approved these changes

2020-12-22 13:12 UTC, merged