INFRA-264 :: Feat - Add a SSM parameter to keep track on versions
PokaInc/cfn-cross-region-export pull request #21
Opened 2021-02-16 20:15 UTC by g-pelletier

2021-02-17 13:28 UTC, daxAKAhackerman approved these changes

2021-02-19 00:21 UTC, laurrentt requested changes

2021-02-19 00:21 UTC, laurrentt commented on Makefile
> +	@sam deploy --template-file $(IMPORTER_GENERATED_TEMPLATE_ABSOLUTE_PATH) --stack-name $(IMPORTER_STACK_NAME) --capabilities CAPABILITY_IAM --parameter-overrides CrossStackRefTableArn=$(CROSS_STACK_R
Should be `Version=$(VERSION)`
```suggestion
	@sam deploy --template-file $(IMPORTER_GENERATED_TEMPLATE_ABSOLUTE_PATH) --stack-name $(IMPORTER_STACK_NAME) --capabilities CAPABILITY_IAM --parameter-overrides CrossStackRefTableArn=$(CROSS_STACK_REF_TABLE_ARN) Version=$(VERSION)
```

2021-02-19 00:21 UTC, laurrentt commented on Makefile
> +	@sam deploy --template-file $(EXPORTER_GENERATED_TEMPLATE_ABSOLUTE_PATH) --stack-name $(EXPORTER_STACK_NAME) --capabilities CAPABILITY_IAM --parameter-overrides SentryDsn=$(SENTRY_DSN) SentryEnviron
```suggestion
	@sam deploy --template-file $(EXPORTER_GENERATED_TEMPLATE_ABSOLUTE_PATH) --stack-name $(EXPORTER_STACK_NAME) --capabilities CAPABILITY_IAM --parameter-overrides SentryDsn=$(SENTRY_DSN) SentryEnvironment=$(SENTRY_ENV) Version=$(VERSION)
```

2021-02-19 15:37 UTC, daxAKAhackerman approved these changes

2021-02-19 18:21 UTC, laurrentt approved these changes

2021-02-19 18:29 UTC, merged